id: IFF601E58
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:27:16.224659'
last_modified: '2022-05-31T05:27:16.224671'
parser: null
source_metadata:
  title: Mipham Rinpoche Series
  language: de
  description: 'Texts by and about the great Nyingma polymath Jamgön Mipham Namgyal
    Gyatso (mi pham rnam rgyal rgya mtsho, 1846-1912), arguably the most influential
    Tibetan scholar of recent times:'
  volume:
    fA879:
      title: Advice for Beginners
      base_file: fA879.txt
      order: 1
      parent: Advice
    f88C3:
      title: Advice to Jigme Tenpe Nyima
      base_file: f88C3.txt
      order: 2
      parent: Advice
    fA551:
      title: Essence of the 84000 Approaches to the Dharma
      base_file: fA551.txt
      order: 3
      parent: Advice
    fE345:
      title: How to Cultivate Concentration
      base_file: fE345.txt
      order: 4
      parent: Advice
    fCC5D:
      title: Profound Instruction on Śamatha
      base_file: fCC5D.txt
      order: 5
      parent: Advice
    f4406:
      title: Satirical Advice for the Four Schools
      base_file: f4406.txt
      order: 6
      parent: Advice
    fE366:
      title: The Four Dharma Traditions of Tibet
      base_file: fE366.txt
      order: 7
      parent: Advice
    f3E3C:
      title: The Importance of Mindfulness and Vigilance
      base_file: f3E3C.txt
      order: 8
      parent: Advice
    fF4E0:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      base_file: fF4E0.txt
      order: 9
      parent: Advice
    f12F7:
      title: The Perfect Equality of the Dharmadhātu
      base_file: f12F7.txt
      order: 10
      parent: Advice
    fCD30:
      title: A Brief Prayer for Summoning Prosperity
      base_file: fCD30.txt
      order: 11
      parent: Aspiration Prayers
    fF57D:
      title: Aspiration for the Four Activities
      base_file: fF57D.txt
      order: 12
      parent: Aspiration Prayers
    f70A4:
      title: Light Offering Prayer
      base_file: f70A4.txt
      order: 13
      parent: Aspiration Prayers
    f4B44:
      title: Sukhāvatī Aspiration
      base_file: f4B44.txt
      order: 14
      parent: Aspiration Prayers
    f6B30:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      base_file: f6B30.txt
      order: 15
      parent: Aspiration Prayers
    f81DA:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      base_file: f81DA.txt
      order: 16
      parent: Aspiration Prayers
    fFFF7:
      title: Verses of the Eight Noble Auspicious Ones
      base_file: fFFF7.txt
      order: 17
      parent: Aspiration Prayers
    fCA4E:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      base_file: fCA4E.txt
      order: 18
      parent: Aspiration Prayers
    f8E43:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      base_file: f8E43.txt
      order: 19
      parent: Averting Obstacles
    f3F04:
      title: Benedictory Verses for A Brilliant Elucidation of Logical Reasoning
      base_file: f3F04.txt
      order: 20
      parent: Benedictory Verses
    f94D4:
      title: Benedictory Verses for White Lotus
      base_file: f94D4.txt
      order: 21
      parent: Benedictory Verses
    fAA3C:
      title: Ascertaining the Two Kinds of Selflessness
      base_file: fAA3C.txt
      order: 22
      parent: Buddhist Philosophy
    f47F7:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      base_file: f47F7.txt
      order: 23
      parent: Buddhist Philosophy
    f4660:
      title: 'Gateway to Learning: Individual Selflessness'
      base_file: f4660.txt
      order: 24
      parent: Buddhist Philosophy
    fA355:
      title: Profound Instruction on the View of the Middle Way
      base_file: fA355.txt
      order: 25
      parent: Buddhist Philosophy
    fDDA9:
      title: Putting the Instruction on the Purification of Mental Activity into Practice
      base_file: fDDA9.txt
      order: 26
      parent: Buddhist Philosophy
    f9D35:
      title: The Sword of Wisdom for Thoroughly Ascertaining Reality
      base_file: f9D35.txt
      order: 27
      parent: Buddhist Philosophy
    f4062:
      title: 'The Vajra Mirror: Cutting through Doubts Concerning Self-Awareness'
      base_file: f4062.txt
      order: 28
      parent: Buddhist Philosophy
    fB4B2:
      title: The Wheel of Analytical Meditation That Thoroughly Purifies Mental Activity
      base_file: fB4B2.txt
      order: 29
      parent: Buddhist Philosophy
    fA74A:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      base_file: fA74A.txt
      order: 30
      parent: Dharma Protectors
    fFC0D:
      title: Brief Offering Prayer to Ekajaṭī
      base_file: fFC0D.txt
      order: 31
      parent: Dharma Protectors
    f54B5:
      title: Brief Offering Prayer to Tsiu Marpo
      base_file: f54B5.txt
      order: 32
      parent: Dharma Protectors
    f2224:
      title: Brief Offering Prayer to Za Rāhula
      base_file: f2224.txt
      order: 33
      parent: Dharma Protectors
    f9B37:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      base_file: f9B37.txt
      order: 34
      parent: Dharma Protectors
    fB474:
      title: Offering to the Five Mentsün Sisters, Guardians of the Earth
      base_file: fB474.txt
      order: 35
      parent: Dharma Protectors
    f0A21:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      base_file: f0A21.txt
      order: 36
      parent: Dzogchen
    fFB1E:
      title: Pith Instruction on the Three Crucial Statements
      base_file: fFB1E.txt
      order: 37
      parent: Dzogchen
    f5D73:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      base_file: f5D73.txt
      order: 38
      parent: Dzogchen
    fAE6E:
      title: The Essence of Mind
      base_file: fAE6E.txt
      order: 39
      parent: Dzogchen
    f3C47:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      base_file: f3C47.txt
      order: 40
      parent: Dzogchen
    f6292:
      title: The Key Points of Trekchö
      base_file: f6292.txt
      order: 41
      parent: Dzogchen
    f43FD:
      title: The Nature of Mind
      base_file: f43FD.txt
      order: 42
      parent: Dzogchen
    f4CFD:
      title: Brief Gesar Windhorse Invocation
      base_file: f4CFD.txt
      order: 43
      parent: Gesar
    fC189:
      title: Brief Offering Prayer to Gesar
      base_file: fC189.txt
      order: 44
      parent: Gesar
    f0481:
      title: Descent of the Compassionate Blessings of King Gesar, Great Lion of this
        World
      base_file: f0481.txt
      order: 45
      parent: Gesar
    f42F4:
      title: Great Clouds of First-Portion Offerings for Prosperity
      base_file: f42F4.txt
      order: 46
      parent: Gesar
    f3368:
      title: Prayer to Gesar
      base_file: f3368.txt
      order: 47
      parent: Gesar
    fADBA:
      title: Short Windhorse Prayer to Gesar
      base_file: fADBA.txt
      order: 48
      parent: Gesar
    f85A3:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      base_file: f85A3.txt
      order: 49
      parent: Gesar
    f2090:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      base_file: f2090.txt
      order: 50
      parent: Gesar
    f1218:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      base_file: f1218.txt
      order: 51
      parent: Gesar
    fB8A3:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      base_file: fB8A3.txt
      order: 52
      parent: Gesar
    f195D:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      base_file: f195D.txt
      order: 53
      parent: Gesar
    fD939:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      base_file: fD939.txt
      order: 54
      parent: Guru Yoga
    f719A:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      base_file: f719A.txt
      order: 55
      parent: Guru Yoga
    f6C36:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      base_file: f6C36.txt
      order: 56
      parent: Guru Yoga
    f67DC:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      base_file: f67DC.txt
      order: 57
      parent: Guru Yoga
    f98FA:
      title: Guru Yoga Focusing upon Noble Kurukullā
      base_file: f98FA.txt
      order: 58
      parent: Guru Yoga
    fC7A3:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      base_file: fC7A3.txt
      order: 59
      parent: Guru Yoga
    fE466:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      base_file: fE466.txt
      order: 60
      parent: Guru Yoga
    fEAF0:
      title: Short Sang Offering to Kurukullā
      base_file: fEAF0.txt
      order: 61
      parent: Kurukullā
    f8CC3:
      title: Short Torma Offering to Kurukullā
      base_file: f8CC3.txt
      order: 62
      parent: Kurukullā
    fE8B8:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      base_file: fE8B8.txt
      order: 63
      parent: Kurukullā
    f7C48:
      title: Brief Dzogchen Lineage Prayer
      base_file: f7C48.txt
      order: 64
      parent: Lineage Prayers
    f9D39:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      base_file: f9D39.txt
      order: 65
      parent: Lineage Prayers
    fF784:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      base_file: fF784.txt
      order: 66
      parent: Long Life Prayers
    f9C8B:
      title: Extemporary Practice of Longevity for Oneself or Others
      base_file: f9C8B.txt
      order: 67
      parent: Longevity
    f7F63:
      title: Brief Windhorse Invocation
      base_file: f7F63.txt
      order: 68
      parent: Lungta
    f94E6:
      title: Daily Lungta Recitation
      base_file: f94E6.txt
      order: 69
      parent: Lungta
    f346B:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      base_file: f346B.txt
      order: 70
      parent: Lungta
    fB465:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      base_file: fB465.txt
      order: 71
      parent: Mantras
    fD98F:
      title: Wrathful Guru Mantra Visualization
      base_file: fD98F.txt
      order: 72
      parent: Mantras
    f14FD:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      base_file: f14FD.txt
      order: 73
      parent: Offering
    fF0DF:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      base_file: fF0DF.txt
      order: 74
      parent: Praise
    f4F1F:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      base_file: f4F1F.txt
      order: 75
      parent: Praise
    fEC7F:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      base_file: fEC7F.txt
      order: 76
      parent: Praise
    fA9AC:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      base_file: fA9AC.txt
      order: 77
      parent: Praise
    fDD00:
      title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
      base_file: fDD00.txt
      order: 78
      parent: Prayers
    fAEA7:
      title: Prayer to Akṣobhya
      base_file: fAEA7.txt
      order: 79
      parent: Prayers
    f5289:
      title: Prayer to Smṛtijñānakīrti
      base_file: f5289.txt
      order: 80
      parent: Prayers
    fAE25:
      title: Three Prayers from the Earth Pig Year
      base_file: fAE25.txt
      order: 81
      parent: Prayers
    f4986:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      base_file: f4986.txt
      order: 82
      parent: Prayers
    fB8F8:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      base_file: fB8F8.txt
      order: 83
      parent: Prayers to Guru Rinpoche
    f3DCC:
      title: Recollecting the Deeds of The Tenth Days
      base_file: f3DCC.txt
      order: 84
      parent: Prayers to Guru Rinpoche
    f3800:
      title: The Prayer which is the Source of All True Realization
      base_file: f3800.txt
      order: 85
      parent: Prayers to Guru Rinpoche
    f76AA:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      base_file: f76AA.txt
      order: 86
      parent: Prayers to Mañjuśrī
    fFE99:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      base_file: fFE99.txt
      order: 87
      parent: Prayers to Mañjuśrī
    f58D1:
      title: In Praise of the Protector Mañjughoṣa
      base_file: f58D1.txt
      order: 88
      parent: Prayers to Mañjuśrī
    fCCDB:
      title: Prayer to Mañjuśrī
      base_file: fCCDB.txt
      order: 89
      parent: Prayers to Mañjuśrī
    fD6A0:
      title: 'Unchanging Auspiciousness: In Praise of Mañjuśrī'
      base_file: fD6A0.txt
      order: 90
      parent: Prayers to Mañjuśrī
    fC380:
      title: Prayer to the Sovereign of Dharma and Retinue
      base_file: fC380.txt
      order: 91
      parent: Prayers to Śākyamuni
    f4044:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      base_file: f4044.txt
      order: 92
      parent: Prayers to Śākyamuni
    fCFBC:
      title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
      base_file: fCFBC.txt
      order: 93
      parent: Preliminary Practice
    fFBE6:
      title: A Sādhana of Jambhala
      base_file: fFBE6.txt
      order: 94
      parent: Sādhanas
    fD832:
      title: A Sādhana of Kurukullā
      base_file: fD832.txt
      order: 95
      parent: Sādhanas
    f9614:
      title: A Sādhana of Sitātapatrā
      base_file: f9614.txt
      order: 96
      parent: Sādhanas
    fEB22:
      title: A Sādhana of White Sarasvatī
      base_file: fEB22.txt
      order: 97
      parent: Sādhanas
    f25BA:
      title: Acala Sādhana
      base_file: f25BA.txt
      order: 98
      parent: Sādhanas
    f77E8:
      title: Kṣitigarbha Visualization and Mantra Recitation
      base_file: f77E8.txt
      order: 99
      parent: Sādhanas
    f9884:
      title: Sādhana of Mārīcī
      base_file: f9884.txt
      order: 100
      parent: Sādhanas
    f0228:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      base_file: f0228.txt
      order: 101
      parent: Sādhanas
    fBBEB:
      title: Brief Sang Offering
      base_file: fBBEB.txt
      order: 102
      parent: Sang Offering
    fF408:
      title: Brief Sang Offering to Purify Contamination
      base_file: fF408.txt
      order: 103
      parent: Sang Offering
    f88D8:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      base_file: f88D8.txt
      order: 104
      parent: Saving Lives
    fB091:
      title: Five-Verse Doha of Yogic Realization
      base_file: fB091.txt
      order: 105
      parent: Songs
    f2FE4:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      base_file: f2FE4.txt
      order: 106
      parent: Sur Offering
    f88ED:
      title: Prayer to Tārā, Combined with Her Mantra
      base_file: f88ED.txt
      order: 107
      parent: Tārā
    fEE44:
      title: Outline of the Ten Royal Sūtras
      base_file: fEE44.txt
      order: 108
      parent: Topical Outlines
    f0432:
      title: Concise Tsok Feast
      base_file: f0432.txt
      order: 109
      parent: Tsok
    f81F1:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      base_file: f81F1.txt
      order: 110
      parent: Tsok
    fE342:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      base_file: fE342.txt
      order: 111
      parent: Vajrasattva
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
